
version: "3.3"
services:
  nginx:
    image: xahhy/todo-react-service
    ports:
      - "80:80"
    depends_on:
      - "zuul-service"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - todo
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    restart: always
    networks:
      - todo
  
  user-service:
    image: xahhy/todo-user-service
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - "config-service"
      - "mysql"
    networks:
      - todo
  

  todo-service:
    image: xahhy/todo-todo-service
    restart: always
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - "config-service"
      - "mysql"
    networks:
      - todo
  
  zuul-service:
    image: xahhy/todo-zuul-service
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - "config-service"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - todo
  
  config-service:
    image: xahhy/todo-config-service
    restart: on-failure
    ports:
      - "8888:8888"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - todo
  

networks:
  todo:
