
version: "3.3"
services:
  nginx:
    image: nginx:1.15.4-alpine
    volumes:
      - ../todo-react-app/build:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - "zuul-service"
    deploy:
      restart_policy:
        condition: on-failure
  
  mysql:
    image: mysql:5.7
    volumes:
      - /Users/hoyhe/Docker/mysql/datadir-pro:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    restart: always
    
  user-service:
    image: todo-user-service
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - "config-service"
      - "mysql"

  todo-service:
    image: todo-todo-service
    restart: always
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - "config-service"
      - "mysql"
  
  zuul-service:
    image: todo-zuul-service
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - "config-service"
    deploy:
      restart_policy:
        condition: on-failure

  config-service:
    image: todo-config-service
    restart: on-failure
    ports:
      - "8888:8888"
    deploy:
      restart_policy:
        condition: on-failure


